---
    
- name: Download binary dependencies
  delegate_to: localhost
  import_tasks: dependencies.yml

- name: Download and configure docker service
  import_tasks: setup-docker.yml

- name: Generates RKE Config
  delegate_to: localhost
  import_tasks: rke-config.yml

  #- name: Spin up RKE cluster and verify 
  # delegate_to: localhost
  # import_tasks: rke-up.yml

